export type Team={id:number;name:string;abbr:string;league:'AL'|'NL';division:string;color:string;venue:string};
const rows:[number,string,string,'AL'|'NL',string,string,string][]=[
[110,'Baltimore Orioles','BAL','AL','East','#df4601','Oriole Park'],[111,'Boston Red Sox','BOS','AL','East','#bd3039','Fenway Park'],[147,'New York Yankees','NYY','AL','East','#0c2340','Yankee Stadium'],[139,'Tampa Bay Rays','TB','AL','East','#8fbce6','George M. Steinbrenner Field'],[141,'Toronto Blue Jays','TOR','AL','East','#134a8e','Rogers Centre'],
[145,'Chicago White Sox','CWS','AL','Central','#27251f','Rate Field'],[114,'Cleveland Guardians','CLE','AL','Central','#e31937','Progressive Field'],[116,'Detroit Tigers','DET','AL','Central','#fa4616','Comerica Park'],[118,'Kansas City Royals','KC','AL','Central','#004687','Kauffman Stadium'],[142,'Minnesota Twins','MIN','AL','Central','#d31145','Target Field'],
[117,'Houston Astros','HOU','AL','West','#eb6e1f','Daikin Park'],[108,'Los Angeles Angels','LAA','AL','West','#ba0021','Angel Stadium'],[133,'Athletics','ATH','AL','West','#003831','Sutter Health Park'],[136,'Seattle Mariners','SEA','AL','West','#005c5c','T-Mobile Park'],[140,'Texas Rangers','TEX','AL','West','#003278','Globe Life Field'],
[144,'Atlanta Braves','ATL','NL','East','#ce1141','Truist Park'],[146,'Miami Marlins','MIA','NL','East','#00a3e0','loanDepot park'],[121,'New York Mets','NYM','NL','East','#ff5910','Citi Field'],[143,'Philadelphia Phillies','PHI','NL','East','#e81828','Citizens Bank Park'],[120,'Washington Nationals','WSH','NL','East','#ab0003','Nationals Park'],
[112,'Chicago Cubs','CHC','NL','Central','#0e3386','Wrigley Field'],[113,'Cincinnati Reds','CIN','NL','Central','#c6011f','Great American Ball Park'],[158,'Milwaukee Brewers','MIL','NL','Central','#ffc52f','American Family Field'],[134,'Pittsburgh Pirates','PIT','NL','Central','#fdb827','PNC Park'],[138,'St. Louis Cardinals','STL','NL','Central','#c41e3a','Busch Stadium'],
[109,'Arizona Diamondbacks','AZ','NL','West','#a71930','Chase Field'],[115,'Colorado Rockies','COL','NL','West','#8b8d8e','Coors Field'],[119,'Los Angeles Dodgers','LAD','NL','West','#005a9c','Dodger Stadium'],[135,'San Diego Padres','SD','NL','West','#ffc425','Petco Park'],[137,'San Francisco Giants','SF','NL','West','#fd5a1e','Oracle Park']];
export const teams:Team[]=rows.map(([id,name,abbr,league,division,color,venue])=>({id,name,abbr,league,division,color,venue}));
export const logo=(id:number)=>`https://www.mlbstatic.com/team-logos/${id}.svg`;
