const IMAGE_ASSET_BY_SLUG: Record<string, string> = {
  "cloaking-device-light": "light/specializations/cloaking-device.png",
  "evasive-dash-light": "light/specializations/evasive-dash.png",
  "grappling-hook-light": "light/specializations/grappling-hook.png",
  "breach-charge-light": "light/gadgets/breach-charge.png",
  "flashbang-light": "light/gadgets/flashbang.png",
  "frag-grenade-light": "light/gadgets/frag-grenade.png",
  "gas-grenade-light": "light/gadgets/gas-grenade.png",
  "gateway-light": "light/gadgets/gateway.png",
  "glitch-grenade-light": "light/gadgets/glitch-grenade.png",
  "goo-grenade-light": "light/gadgets/goo-grenade.png",
  "gravity-vortex-light": "light/gadgets/gravity-vortex.png",
  "h-plus-infuser": "light/gadgets/h-plus-infuser.png",
  "nullifier-light": "light/gadgets/nullifier.png",
  "pyro-grenade-light": "light/gadgets/pyro-grenade.png",
  "smoke-grenade-light": "light/gadgets/smoke-grenade.png",
  "sonar-grenade-light": "light/gadgets/sonar-grenade.png",
  "thermal-bore-light": "light/gadgets/thermal-bore.png",
  "thermal-vision-light": "light/gadgets/thermal-vision.png",
  "tracking-dart-light": "light/gadgets/tracking-dart.png",
  "vanishing-bomb-light": "light/gadgets/vanishing-bomb.png",
  "dematerializer-medium": "medium/specializations/dematerializer.png",
  "guardian-turret-medium": "medium/specializations/guardian-turret.png",
  "healing-beam-medium": "medium/specializations/healing-beam.png",
  "shockwave-medium": "medium/specializations/shockwave.png",
  "recon-senses-medium": "medium/specializations/recon-senses.png",
  "aps-turret-medium": "medium/gadgets/aps-turret.png",
  "breach-drill-medium": "medium/gadgets/breach-drill.png",
  "data-reshaper-medium": "medium/gadgets/data-reshaper.png",
  "defibrillator-medium": "medium/gadgets/defibrillator.png",
  "explosive-mine-medium": "medium/gadgets/explosive-mine.png",
  "flashbang-medium": "medium/gadgets/flashbang.png",
  "frag-grenade-medium": "medium/gadgets/frag-grenade.png",
  "gas-grenade-medium": "medium/gadgets/gas-grenade.png",
  "gas-mine-medium": "medium/gadgets/gas-mine.png",
  "glitch-trap-medium": "medium/gadgets/glitch-trap.png",
  "goo-grenade-medium": "medium/gadgets/goo-grenade.png",
  "hover-pad-medium": "medium/gadgets/hover-pad.png",
  "jump-pad-medium": "medium/gadgets/jump-pad.png",
  "proximity-sensor-medium": "medium/gadgets/proximity-sensor.png",
  "pyro-grenade-medium": "medium/gadgets/pyro-grenade.png",
  "zipline-medium": "medium/gadgets/zipline.png",
  "smoke-grenade-medium": "medium/gadgets/smoke-grenade.png",
  "night-vision-medium": "medium/gadgets/night-vision.png",
  "charge-n-slam-heavy": "heavy/specializations/charge-n-slam.png",
  "goo-gun-heavy": "heavy/specializations/goo-gun.png",
  "mesh-shield-heavy": "heavy/specializations/mesh-shield.png",
  "winch-claw-heavy": "heavy/specializations/winch-claw.png",
  "anti-gravity-cube-heavy": "heavy/gadgets/anti-gravity-cube.png",
  "barricade-heavy": "heavy/gadgets/barricade.png",
  "c4-heavy": "heavy/gadgets/c4.png",
  "dome-shield-heavy": "heavy/gadgets/dome-shield.png",
  "explosive-mine-heavy": "heavy/gadgets/explosive-mine.png",
  "flashbang-heavy": "heavy/gadgets/flashbang.png",
  "frag-grenade-heavy": "heavy/gadgets/frag-grenade.png",
  "gas-grenade-heavy": "heavy/gadgets/gas-grenade.png",
  "goo-grenade-heavy": "heavy/gadgets/goo-grenade.png",
  "healing-emitter-heavy": "heavy/gadgets/healing-emitter.png",
  "proximity-sensor-heavy": "heavy/gadgets/proximity-sensor.png",
  "pyro-grenade-heavy": "heavy/gadgets/pyro-grenade.png",
  "pyro-mine-heavy": "heavy/gadgets/pyro-mine.png",
  "rpg-7-heavy": "heavy/gadgets/rpg-7.png",
  "smoke-grenade-heavy": "heavy/gadgets/smoke-grenade.png",
  "lockbolt-heavy": "heavy/gadgets/lockbolt.png",
  "night-vision-heavy": "heavy/gadgets/night-vision.png",
};

export function resolveWeaponArchiveImageUrl(slug: string, seedImageUrl: string | null | undefined) {
  if (seedImageUrl) return seedImageUrl;
  const assetPath = IMAGE_ASSET_BY_SLUG[slug];
  return assetPath ? `/images/weapons/${assetPath}` : null;
}
